apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stressor-app
  template:
    metadata:
      labels:
        app: stressor-app
    spec:
      serviceAccountName: stressor-app-sa
      serviceAccount: stressor-app-sa
      containers:
      - name: stressor-app
        image: *****
        ports:
          - name: http
            containerPort: 8080
          - name: metrics
            containerPort: 9249
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
