apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stressor-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stressor-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: stressor_metric
      target:
        type: AverageValue
        averageValue: 10
