apiVersion: v1
kind: Service
metadata:
  name: stressor-app
spec:
  selector:
    app: stressor-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9249
      targetPort: 9249
