apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stressor-app
  labels:
    app: stressor-app
spec:
  selector:
    matchLabels:
      app: stressor-app
  endpoints:
  - port: 8080
    path: /metrics
